{% set name = "leather" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f964bec2086f3153a6c16e707f20cb718f811f57af116075f4c0f4805c608b95

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - leather
    - leather.axis
    - leather.chart
    - leather.data_types
    - leather.grid
    - leather.lattice
    - leather.scales
    - leather.scales.base
    - leather.scales.linear
    - leather.scales.ordinal
    - leather.scales.temporal
    - leather.series
    - leather.series.base
    - leather.series.category
    - leather.shapes
    - leather.shapes.bars
    - leather.shapes.base
    - leather.shapes.columns
    - leather.shapes.dots
    - leather.shapes.line
    - leather.svg
    - leather.testcase
    - leather.ticks.base
    - leather.ticks.score
    - leather.ticks.score_time
    - leather.utils
  requires:
    - pip
    - pytest
    - lxml >=3.6.0
    - cssselect >=0.9.1
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://leather.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python charting for 80% of humans.
  description: |
    Leather is the Python charting library for those who need charts now and don't care if they're perfect.
    Leather isn't picky. It's rough. It gets dirty. It looks sexy just hanging on the back of a chair.
    Leather doesn't need your accessories. Leather is how Snake Plissken would make charts.
  doc_url: https://leather.readthedocs.io
  dev_url: https://github.com/wireservice/leather

extra:
  recipe-maintainers:
    - pmlandwehr