{% set version = "0.3.3" %}

package:
  name: leather
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/leather/leather-{{ version }}.tar.gz
  sha256: 076d1603b5281488285718ce1a5ce78cf1027fe1e76adf9c548caf83c519b988

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - six >=1.6.1
  run:
    - python
    - six >=1.6.1

test:
  imports:
    - leather
    - leather.scales
    - leather.series
    - leather.shapes
    - leather.ticks

about:
  home: https://leather.rtfd.io
  license: MIT
  license_family: MIT
  # license_file: COPYING - no MANIFEST - see https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options
  summary: 'Python charting for 80% of humans.'
  doc_url: https://leather.rtfd.io
  dev_url: https://github.com/wireservice/leather

extra:
  recipe-maintainers:
    - pmlandwehr
