travis:
  secure:
    BINSTAR_TOKEN: nJauQ9zclTnmz5aDEU9WGdeTDhfIHQwFU6g9AETorH+HGkIZ1qct/vZyWS33vWSt+kMSjc1ggYge/DAdI+I7wbDpiWYSmPCGxLnlyvNGll+E4cDYE02SIZExfemfuZR766TzO7gOqNXGgPWHU9WMEOWhmbF16xIKQ77wXlAOnqZmboAtMLdG9dUWyM/fsjFp+VjUwA78VVu6njNeKZ78zOQj//aT9aeqz0WXBLRzxjuiPhCvS0HpWTVhpCaRdx/En7mlp2GVUuUXXo3BUq0c7Yy2RGhHTrlifVhSBelTd7JjSg9JBtAJZ91WQMUrbFUU7lscw/SlpG/6SpMyeW7taf/GGagZlyt8m8tlyM+CBCMtgAX5AjdobgpROXJWkJcvac94XmxTrG2mdzV5N89/UkTakT+Koe+rfG44lFnESeXqIxKbuSt+v0euAktuaj8zbnpdIBy5TH/RbysUcz4xxukx0atdi2DH9YTZogejgxPn2Q5eMy/cpvwbRvAGVbx9G2pm/aaIVOHL29U9zzStR47F6p9OPUAIH+4GfQCF5tFcQn1X74TzSoZbi/EgBoTSSleE3+8NTQ9gN8IcKVcEtbSSlcqs0kcg1+qws+CNQ+YoBrI8qwNT34HpFTm8kvApUJmo3fffo9+WBmi3jNmQewpDl0O5XwZo0+jxyErpZaI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
