travis:
  secure:
    BINSTAR_TOKEN: bpDiOKneVrYFx1bIiPouvC01tuk2SZdu1drPE2ThMWYUvDQtwSVH/0PwoGodvYbArapBGP5NrdVyI5dJRsV0PxupmI5hc+QIIMxF0+0Iy4Zv0xavdJFgxGb0bZ6MGU49WwDMaRNS3HD2FIvWpZwAev2s4Ba0I+exs0UEdV/pnLGwQkgTYCuJb82HKu9D1XYjBELZ375p2GmX2+LdKTnt/w5iyrKY0xe9ZEj6oG9jPW5gSDrhQ3OhOWaB5/fnviJ+7mZBAYjetwkhGbVTQCZPk1tvheGsj7l3N2JmWlJtzgN8ioBMmuEV4uJ1ItR7+G60yceW1/a25ut01wLHv8jFx7QOZn5yck/C4rS3HFRz98ufx7Oh/ASRE+3ZmUnW6Nx5k1RnNrsnpWUdJvvCB8J+grMyrCkCBu5pCHGjpTLfv+pO8cJa8jqFZJ7oHq0FcCmRspoJqCIaEaWA/oFg5LUJJeuuLxAY04Hlt8pY3tM3WJuXgUykvhXDuVGWDlRxZ+GLEtaChFD1PM/grs8oU0eGnrIgIJPqKrUAccpa/TvGGkgPBpodYEpgKAK/v38WtAgS8x04PTGVACHGDZ98YqCnGlo9zLoD8MHnyLGHorhMFVxGUbJVg5uBFFVqvKT7V2K9po75499yqTv7u5KDxgu3u56JxrYaR6HUzx9nIYhLsfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
