travis:
  secure:
    BINSTAR_TOKEN: Bze8zdOdbHXchpgrAo7yQkcT2pKbsPEA6lZUs8bBDcbMfJGCxuaCNZqpuBWgPVgYjrXbLcijXGlZur7EQaIyBoLalnd4lz6dqFc2ybEnUsClVvUUdmBcekCkXhlPvtIbI1CU9pxXsv873C0cIxdCZNQ/srT48vuFq3lPDW1w61ZXJgd/tQzuY4rsWN6Td6FPLgqXwrhzGYx3sVjEI6M8BlSp8QY4KM6K8Jp4fcmFySwqpVidsQwaPeyFeiw4liAjYnv05XLZfO+0WlbIBXUJXMHfB1KJlN03ds9BFCGFhI3lQpR20by0Ahl3+9CWT32YbpODjWzyH/Osz3R8kfK0n+9dxr65OkNsRyhxfA6om6fjTZ/mcpqoUd0UmQZSDfVx8mo5vlbe1ZOypsfpWuVoGcS7AH/E52WkY7vPXVGV9sLYL6f7PyYBsxGg5jWU8ILirqrxCHcomRmPKSqRYYOdfQJJewnoE7Xn96So8asgQ84owjakVNab1XB21i9PjEKUKBZQc92dM2SUAZ46Dsv4H1sT5UA+qbwmVeV43qF6B2s5gCEFjkGbDiebPrSebzzdUSOYvBU74bq98XE2CbM5QQRiSQy1LNWbW6qoqwnzFO4gv4V5UnOyRICs3lP7N+5HPJgbaChtl1lMfmBxmq5gb0rnrxJdR3z1up18WFYLoD8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
